POST https://node-do-zero-1doj.onrender.com/videos
Content-Type: application/json

{
  "title": "Video 100",
  "description": "this is my video",
  "duration": 300
}

###

GET https://node-do-zero-1doj.onrender.com/videos

###

PUT https://node-do-zero-1doj.onrender.com/videos/788c513c-598f-4674-8a8f-0819342bd3a3
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Esse e o segundo video",
  "duration": 200
}

###
DELETE https://node-do-zero-1doj.onrender.com/videos/788c513c-598f-4674-8a8f-0819342bd3a3